local LSM = LibStub("LibSharedMedia-3.0")
local koKR, ruRU, zhCN, zhTW, western = LSM.LOCALE_BIT_koKR, LSM.LOCALE_BIT_ruRU, LSM.LOCALE_BIT_zhCN, LSM.LOCALE_BIT_zhTW, LSM.LOCALE_BIT_western

local MediaType_BACKGROUND = LSM.MediaType.BACKGROUND or "background"
local MediaType_BORDER = LSM.MediaType.BORDER or "border"
local MediaType_FONT = LSM.MediaType.FONT or "font"
local MediaType_STATUSBAR = LSM.MediaType.STATUSBAR or "statusbar"
local MediaType_SOUND = LSM.MediaType.SOUND or "sound"

LSM:Register(MediaType_STATUSBAR, 'Asphyxia', [[Interface\AddOns\VSM\Media\StatusBars\Asphyxia]])
LSM:Register(MediaType_STATUSBAR, 'Bezo', [[Interface\AddOns\VSM\Media\StatusBars\Bezo]])
LSM:Register(MediaType_STATUSBAR, 'Dajova', [[Interface\AddOns\VSM\Media\StatusBars\Dajova]])
LSM:Register(MediaType_STATUSBAR, 'Duffed', [[Interface\AddOns\VSM\Media\StatusBars\Duffed]])
LSM:Register(MediaType_STATUSBAR, 'Flatt', [[Interface\AddOns\VSM\Media\StatusBars\Flatt]])
LSM:Register(MediaType_STATUSBAR, 'Sinaris', [[Interface\AddOns\VSM\Media\StatusBars\Sinaris]])
LSM:Register(MediaType_STATUSBAR, 'Slate', [[Interface\AddOns\VSM\Media\StatusBars\Slate]])
LSM:Register(MediaType_STATUSBAR, 'Smooth', [[Interface\AddOns\VSM\Media\StatusBars\Smooth]])
LSM:Register(MediaType_STATUSBAR, 'Tukui', [[Interface\AddOns\VSM\Media\StatusBars\Tukui]])
LSM:Register(MediaType_STATUSBAR, 'Aluminium Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Aluminium]])
LSM:Register(MediaType_STATUSBAR, 'Asphyxia Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Asphyxia]])
LSM:Register(MediaType_STATUSBAR, 'BantoBar Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\BantoBar]])
LSM:Register(MediaType_STATUSBAR, 'Button Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Button]])
LSM:Register(MediaType_STATUSBAR, 'Cloud Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Cloud]])
LSM:Register(MediaType_STATUSBAR, 'Comet Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Comet]])
LSM:Register(MediaType_STATUSBAR, 'Dabs Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Dabs]])
LSM:Register(MediaType_STATUSBAR, 'ElvUI Gloss Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\ElvUI]])
LSM:Register(MediaType_STATUSBAR, 'Falumn Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Falumn]])
LSM:Register(MediaType_STATUSBAR, 'Flat Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Flat]])
LSM:Register(MediaType_STATUSBAR, 'Frost Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Frost]])
LSM:Register(MediaType_STATUSBAR, 'Glamour Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Glamour]])
LSM:Register(MediaType_STATUSBAR, 'Glamour2 Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Glamour2]])
LSM:Register(MediaType_STATUSBAR, 'Glamour3 Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Glamour3]])
LSM:Register(MediaType_STATUSBAR, 'Glamour4 Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Glamour4]])
LSM:Register(MediaType_STATUSBAR, 'Glamour5 Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Glamour5]])
LSM:Register(MediaType_STATUSBAR, 'Glamour6 Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Glamour6]])
LSM:Register(MediaType_STATUSBAR, 'Glamour7 Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Glamour7]])
LSM:Register(MediaType_STATUSBAR, 'Glaze Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Glaze]])
LSM:Register(MediaType_STATUSBAR, 'Glaze2 Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Glaze2]])
LSM:Register(MediaType_STATUSBAR, 'Gloss Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Gloss]])
LSM:Register(MediaType_STATUSBAR, 'Healbot Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Healbot]])
LSM:Register(MediaType_STATUSBAR, 'LiteStep Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\LiteStep]])
LSM:Register(MediaType_STATUSBAR, 'Lyfe Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Lyfe]])
LSM:Register(MediaType_STATUSBAR, 'Minimalist Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Minimalist]])
LSM:Register(MediaType_STATUSBAR, 'Otravi Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Otravi]])
LSM:Register(MediaType_STATUSBAR, 'Outline Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Outline]])
LSM:Register(MediaType_STATUSBAR, 'Perl Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Perl]])
LSM:Register(MediaType_STATUSBAR, 'Rocks Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Rocks]])
LSM:Register(MediaType_STATUSBAR, 'Round Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Round]])
LSM:Register(MediaType_STATUSBAR, 'Ruben Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Ruben]])
LSM:Register(MediaType_STATUSBAR, 'Runes Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Runes]])
LSM:Register(MediaType_STATUSBAR, 'Sinaris Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Sinaris]])
LSM:Register(MediaType_STATUSBAR, 'Slate Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Slate]])
LSM:Register(MediaType_STATUSBAR, 'Smooth Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Smooth]])
LSM:Register(MediaType_STATUSBAR, 'Tukui Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Tukui]])
LSM:Register(MediaType_STATUSBAR, 'Water Vertical', [[Interface\AddOns\VSM\Media\StatusBars\Vertical\Water]])

LSM:Register(MediaType_FONT, 'Big Noodle Titling', [[Interface\AddOns\VSM\Media\Fonts\BigNoodleTitling.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Big Noodle Too', [[Interface\AddOns\VSM\Media\Fonts\BigNoodleToo.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Dajova', [[Interface\AddOns\VSM\Media\Fonts\Dajova.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Oswald Bold', [[Interface\AddOns\VSM\Media\Fonts\Oswald-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Oswald Light', [[Interface\AddOns\VSM\Media\Fonts\Oswald-Light.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Oswald Regular', [[Interface\AddOns\VSM\Media\Fonts\Oswald-Regular.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Saarland', [[Interface\AddOns\VSM\Media\Fonts\Saarland.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Samson', [[Interface\AddOns\VSM\Media\Fonts\Samson.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Sony Sketch', [[Interface\AddOns\VSM\Media\Fonts\SonySketch.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'PT Sans Narrow Bold', [[Interface\AddOns\VSM\Media\Fonts\PTSansNarrow-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Diediedie', [[Interface\AddOns\VSM\Media\Fonts\Diediedie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Visitor TT2 BRK', [[Interface\AddOns\VSM\Media\Fonts\Visitor.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Homespun TT BRK', [[Interface\AddOns\VSM\Media\Fonts\Homespun.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Action Man', [[Interface\AddOns\VSM\Media\Fonts\ActionMan.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Continuum Medium', [[Interface\AddOns\VSM\Media\Fonts\ContinuumMedium.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Arial', [[Interface\AddOns\VSM\Media\Fonts\Arial.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'KGSmallTownSouthernGirl', [[Interface\AddOns\VSM\Media\Fonts\KGSmallTownSouthernGirl.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Youthanasia Texture', [[Interface\AddOns\VSM\Media\Fonts\YOUTHAN.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Youthanasia Texture Regular', [[Interface\AddOns\VSM\Media\Fonts\YOUTTX.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Good Time', [[Interface\AddOns\VSM\Media\Fonts\GOODTIME.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Reprise Title', [[Interface\AddOns\VSM\Media\Fonts\Reprise Title.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Futurapress', [[Interface\AddOns\VSM\Media\Fonts\Futurapress.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Event Horizon', [[Interface\AddOns\VSM\Media\Fonts\Event Horizon.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'H.H. Samuel', [[Interface\AddOns\VSM\Media\Fonts\H.H. Samuel.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Jacinto Sans', [[Interface\AddOns\VSM\Media\Fonts\Jacinto Sans.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'JUSTICE LEAGUE', [[Interface\AddOns\VSM\Media\Fonts\JUSTICE LEAGUE.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'SF Laundromatic Condensed', [[Interface\AddOns\VSM\Media\Fonts\SF Laundromatic Condensed.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Skipper Stencil', [[Interface\AddOns\VSM\Media\Fonts\skipper_stencil.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Ardnas', [[Interface\AddOns\VSM\Media\Fonts\Ardnas.otf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Impacted', [[Interface\AddOns\VSM\Media\Fonts\Impacted.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Lemondrop', [[Interface\AddOns\VSM\Media\Fonts\Lemondrop.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Mobile Sans', [[Interface\AddOns\VSM\Media\Fonts\Mobile Sans.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Quimbie', [[Interface\AddOns\VSM\Media\Fonts\Quimbie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Monserga Regular', [[Interface\AddOns\VSM\Media\Fonts\Monserga-regular-FFP.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Indulta SemiSerif', [[Interface\AddOns\VSM\Media\Fonts\Indulta-SemiSerif-boldFFP.otf]])
LSM:Register(MediaType_FONT, 'CLUB', [[Interface\AddOns\VSM\Media\Fonts\CLUB____.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Adigiana Ultra', [[Interface\AddOns\VSM\Media\Fonts\Adigiana Ultra.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Tabarra Shadow', [[Interface\AddOns\VSM\Media\Fonts\Tabarra-Shadow-FFP.otf]])
LSM:Register(MediaType_FONT, 'Sturkopf', [[Interface\AddOns\VSM\Media\Fonts\Sturkopf.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Ordinatum Bold', [[Interface\AddOns\VSM\Media\Fonts\Ordinatum_Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Ordinatum Light', [[Interface\AddOns\VSM\Media\Fonts\Ordinatum_Light.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Ordinatum Medium', [[Interface\AddOns\VSM\Media\Fonts\Ordinatum_Medium.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Zektonbo', [[Interface\AddOns\VSM\Media\Fonts\zektonbo.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Aron Grotesque Bold', [[Interface\AddOns\VSM\Media\Fonts\aron_grotesque_bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'AIdealist Sans', [[Interface\AddOns\VSM\Media\Fonts\Idealist Sans.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Sarpanch SemiBold', [[Interface\AddOns\VSM\Media\Fonts\Sarpanch-SemiBold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Semi Casual', [[Interface\AddOns\VSM\Media\Fonts\Semi-Casual.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'futurademic', [[Interface\CustomFonts\Semi-Casual.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'OpenSans-Bold', [[Interface\CustomFonts\OpenSans-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'OpenSans-BoldItalic', [[Interface\CustomFonts\OpenSans-BoldItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'OpenSans-ExtraBold', [[Interface\CustomFonts\OpenSans-ExtraBold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'OpenSans-ExtraBoldItalic', [[Interface\CustomFonts\OpenSans-ExtraBoldItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'OpenSans-Italic', [[Interface\CustomFonts\OpenSans-Italic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'OpenSans-Light', [[Interface\CustomFonts\OpenSans-Light.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'OpenSans-LightItalic', [[Interface\CustomFonts\OpenSans-LightItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'OpenSans-Regular', [[Interface\CustomFonts\OpenSans-Regular.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'OpenSans-Semibold', [[Interface\CustomFonts\OpenSans-Semibold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'OpenSans-SemiboldItalic', [[Interface\CustomFonts\OpenSans-SemiboldItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Supermolot', [[Interface\AddOns\VSM\Media\Fonts\Supermolot.otf]])
LSM:Register(MediaType_FONT, "Accidental Presidency", [[Interface\AddOns\VSM\Media\Fonts\AccidentalPresidency.ttf]])
LSM:Register(MediaType_FONT, "Adventure", [[Interface\AddOns\VSM\Media\Fonts\Adventure.ttf]])
LSM:Register(MediaType_FONT, "Alba Super", [[Interface\AddOns\VSM\Media\Fonts\AlbaSuper.ttf]])
LSM:Register(MediaType_FONT, "All Hooked Up", [[Interface\AddOns\VSM\Media\Fonts\AllHookedUp.ttf]])
LSM:Register(MediaType_FONT, "Ancient Geek", [[Interface\AddOns\VSM\Media\Fonts\AncientGeek.ttf]])
LSM:Register(MediaType_FONT, "Arm Wrestler", [[Interface\AddOns\VSM\Media\Fonts\ArmWrestler.ttf]])
LSM:Register(MediaType_FONT, "Augustus", [[Interface\AddOns\VSM\Media\Fonts\Augustus.ttf]])
LSM:Register(MediaType_FONT, "Aurora", [[Interface\AddOns\VSM\Media\Fonts\Aurora.ttf]])
LSM:Register(MediaType_FONT, "Aurora Extended", [[Interface\AddOns\VSM\Media\Fonts\AuroraExtended.ttf]])
LSM:Register(MediaType_FONT, "AvantGarde LT Medium", [[Interface\AddOns\VSM\Media\Fonts\AvantGardeLTMedium.ttf]])
LSM:Register(MediaType_FONT, "Avanti", [[Interface\AddOns\VSM\Media\Fonts\Avanti.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Baar Sophia", [[Interface\AddOns\VSM\Media\Fonts\BaarSophia.ttf]])
LSM:Register(MediaType_FONT, "Bavaria", [[Interface\AddOns\VSM\Media\Fonts\Bavaria.ttf]])
LSM:Register(MediaType_FONT, "Bavaria Extended", [[Interface\AddOns\VSM\Media\Fonts\BavariaExtended.ttf]])
LSM:Register(MediaType_FONT, "Bazooka", [[Interface\AddOns\VSM\Media\Fonts\Bazooka.ttf]])
LSM:Register(MediaType_FONT, "BigNoodleToo", [[Interface\AddOns\VSM\Media\Fonts\BigNoodleToo.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Black Chancery", [[Interface\AddOns\VSM\Media\Fonts\BlackChancery.ttf]])
LSM:Register(MediaType_FONT, "Blazed", [[Interface\AddOns\VSM\Media\Fonts\Blazed.ttf]])
LSM:Register(MediaType_FONT, "Blender Pro", [[Interface\AddOns\VSM\Media\Fonts\BlenderPro.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Blender Pro Bold", [[Interface\AddOns\VSM\Media\Fonts\BlenderProBold.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Blender Pro Heavy", [[Interface\AddOns\VSM\Media\Fonts\BlenderProHeavy.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Boris Black Bloxx Dirty", [[Interface\AddOns\VSM\Media\Fonts\BorisBlackBloxxDirty.ttf]])
LSM:Register(MediaType_FONT, "Boris Black Bloxx", [[Interface\AddOns\VSM\Media\Fonts\BorisBlackBloxx.ttf]])
LSM:Register(MediaType_FONT, "Caesar", [[Interface\AddOns\VSM\Media\Fonts\Caesar.ttf]])
LSM:Register(MediaType_FONT, "Capitalis Type Oasis", [[Interface\AddOns\VSM\Media\Fonts\CapitalisTypeOasis.ttf]])
LSM:Register(MediaType_FONT, "Celestia Medium Redux", [[Interface\AddOns\VSM\Media\Fonts\CelestiaMediumRedux.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Collegiate", [[Interface\AddOns\VSM\Media\Fonts\Collegiate.ttf]])
LSM:Register(MediaType_FONT, "Continuum Medium", [[Interface\AddOns\VSM\Media\Fonts\ContinuumMedium.ttf]])
LSM:Register(MediaType_FONT, "DejaVu Sans", [[Interface\AddOns\VSM\Media\Fonts\DejaVuLGCSans.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "DejaVu Serif", [[Interface\AddOns\VSM\Media\Fonts\DejaVuLGCSerif.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "DieDieDie", [[Interface\AddOns\VSM\Media\Fonts\DieDieDie.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Diogenes", [[Interface\AddOns\VSM\Media\Fonts\Diogenes.ttf]])
LSM:Register(MediaType_FONT, "Disko", [[Interface\AddOns\VSM\Media\Fonts\Disko.ttf]])
LSM:Register(MediaType_FONT, "Doris PP", [[Interface\AddOns\VSM\Media\Fonts\DorisPP.ttf]])
LSM:Register(MediaType_FONT, "Enigmatic", [[Interface\AddOns\VSM\Media\Fonts\Enigmatic.ttf]])
LSM:Register(MediaType_FONT, "Eurasia", [[Interface\AddOns\VSM\Media\Fonts\Eurasia.ttf]])
LSM:Register(MediaType_FONT, "Exocet Blizzard Light", [[Interface\AddOns\VSM\Media\Fonts\ExocetBlizzardLight.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Exocet Blizzard Medium", [[Interface\AddOns\VSM\Media\Fonts\ExocetBlizzardMedium.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Expressway", [[Interface\AddOns\VSM\Media\Fonts\Expressway.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Fitzgerald", [[Interface\AddOns\VSM\Media\Fonts\Fitzgerald.ttf]])
LSM:Register(MediaType_FONT, "FORCED SQUARE", [[Interface\AddOns\VSM\Media\Fonts\FORCEDSQUARE.ttf]])
LSM:Register(MediaType_FONT, "Frakturika Spamless", [[Interface\AddOns\VSM\Media\Fonts\FrakturikaSpamless.ttf]])
LSM:Register(MediaType_FONT, "FrancoisOne", [[Interface\AddOns\VSM\Media\Fonts\FrancoisOne.ttf]])
LSM:Register(MediaType_FONT, "Frucade", [[Interface\AddOns\VSM\Media\Fonts\Frucade.ttf]])
LSM:Register(MediaType_FONT, "Frucade Small", [[Interface\AddOns\VSM\Media\Fonts\FrucadeSmall.ttf]])
LSM:Register(MediaType_FONT, "Frucade Medium", [[Interface\AddOns\VSM\Media\Fonts\FrucadeMedium.ttf]])
LSM:Register(MediaType_FONT, "Frucade Extended", [[Interface\AddOns\VSM\Media\Fonts\FrucadeExtended.ttf]])
LSM:Register(MediaType_FONT, "Futura PT Bold", [[Interface\AddOns\VSM\Media\Fonts\FuturaPTBold.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Futura PT Book", [[Interface\AddOns\VSM\Media\Fonts\FuturaPTBook.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Futura PT Medium", [[Interface\AddOns\VSM\Media\Fonts\FuturaPTMedium.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Gentium Plus", [[Interface\AddOns\VSM\Media\Fonts\GentiumPlus.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Germanica Embossed", [[Interface\AddOns\VSM\Media\Fonts\GermanicaEmbossed.ttf]])
LSM:Register(MediaType_FONT, "Germanica Fluted", [[Interface\AddOns\VSM\Media\Fonts\GermanicaFluted.ttf]])
LSM:Register(MediaType_FONT, "Germanica Shadowed", [[Interface\AddOns\VSM\Media\Fonts\GermanicaShadowed.ttf]])
LSM:Register(MediaType_FONT, "Gotham Ultra", [[Interface\AddOns\VSM\Media\Fonts\GothamUltra.ttf]])
LSM:Register(MediaType_FONT, "Gros", [[Interface\AddOns\VSM\Media\Fonts\Gros.ttf]])
LSM:Register(MediaType_FONT, "Gros Extended", [[Interface\AddOns\VSM\Media\Fonts\GrosExtended.ttf]])
LSM:Register(MediaType_FONT, "Hack", [[Interface\AddOns\VSM\Media\Fonts\Hack.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Harry Potter", [[Interface\AddOns\VSM\Media\Fonts\HarryP.ttf]])
LSM:Register(MediaType_FONT, "Homespun", [[Interface\AddOns\VSM\Media\Fonts\Homespun.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Impact", [[Interface\AddOns\VSM\Media\Fonts\Impact.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "King Arthur Legend", [[Interface\AddOns\VSM\Media\Fonts\KingArthurLegend.ttf]])
LSM:Register(MediaType_FONT, "Liberation Sans", [[Interface\AddOns\VSM\Media\Fonts\LiberationSans.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Liberation Serif", [[Interface\AddOns\VSM\Media\Fonts\LiberationSerif.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Marke Eigenbau", [[Interface\AddOns\VSM\Media\Fonts\MarkeEigenbau.ttf]])
LSM:Register(MediaType_FONT, "Memoria Extended", [[Interface\AddOns\VSM\Media\Fonts\MemoriaExtended.ttf]])
LSM:Register(MediaType_FONT, "Memoria", [[Interface\AddOns\VSM\Media\Fonts\Memoria.ttf]])
LSM:Register(MediaType_FONT, "Micro", [[Interface\AddOns\VSM\Media\Fonts\Micro.ttf]])
LSM:Register(MediaType_FONT, "Munica Extended", [[Interface\AddOns\VSM\Media\Fonts\MunicaExtended.ttf]])
LSM:Register(MediaType_FONT, "Munica", [[Interface\AddOns\VSM\Media\Fonts\Munica.ttf]])
LSM:Register(MediaType_FONT, "Mystic Orbs", [[Interface\AddOns\VSM\Media\Fonts\MysticOrbs.ttf]])
LSM:Register(MediaType_FONT, "Nueva Std Cond", [[Interface\AddOns\VSM\Media\Fonts\NuevaStdCond.ttf]])
LSM:Register(MediaType_FONT, "Olde English", [[Interface\AddOns\VSM\Media\Fonts\OldeEnglish.ttf]])
LSM:Register(MediaType_FONT, "Oswald", [[Interface\AddOns\VSM\Media\Fonts\Oswald.ttf]])
LSM:Register(MediaType_FONT, "Pokemon Solid", [[Interface\AddOns\VSM\Media\Fonts\PokemonSolid.ttf]])
LSM:Register(MediaType_FONT, "Porky", [[Interface\AddOns\VSM\Media\Fonts\Porky.ttf]])
LSM:Register(MediaType_FONT, "PT Sans Narrow", [[Interface\AddOns\VSM\Media\Fonts\PTSansNarrow.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Quicksand", [[Interface\AddOns\VSM\Media\Fonts\Quicksand.ttf]])
LSM:Register(MediaType_FONT, "Rock Show Whiplash", [[Interface\AddOns\VSM\Media\Fonts\RockShowWhiplash.ttf]])
LSM:Register(MediaType_FONT, "Roman SD", [[Interface\AddOns\VSM\Media\Fonts\RomanSD.ttf]])
LSM:Register(MediaType_FONT, "Romanum Est", [[Interface\AddOns\VSM\Media\Fonts\RomanumEst.ttf]])
LSM:Register(MediaType_FONT, "Semplice Extended", [[Interface\AddOns\VSM\Media\Fonts\SempliceExtended.ttf]])
LSM:Register(MediaType_FONT, "Semplice", [[Interface\AddOns\VSM\Media\Fonts\Semplice.ttf]])
LSM:Register(MediaType_FONT, "SF Atarian System", [[Interface\AddOns\VSM\Media\Fonts\SFAtarianSystem.ttf]])
LSM:Register(MediaType_FONT, "SF Covington", [[Interface\AddOns\VSM\Media\Fonts\SFCovington.ttf]])
LSM:Register(MediaType_FONT, "SF Diego Sans", [[Interface\AddOns\VSM\Media\Fonts\SFDiegoSans.ttf]])
LSM:Register(MediaType_FONT, "SF Movie Poster", [[Interface\AddOns\VSM\Media\Fonts\SFMoviePoster.ttf]])
LSM:Register(MediaType_FONT, "SF Wonder Comic", [[Interface\AddOns\VSM\Media\Fonts\SFWonderComic.ttf]])
LSM:Register(MediaType_FONT, "Solange", [[Interface\AddOns\VSM\Media\Fonts\Solange.ttf]])
LSM:Register(MediaType_FONT, "Star Cine", [[Interface\AddOns\VSM\Media\Fonts\StarCine.ttf]])
LSM:Register(MediaType_FONT, "Steelfish Rg", [[Interface\AddOns\VSM\Media\Fonts\SteelfishRg.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "SWF!T", [[Interface\AddOns\VSM\Media\Fonts\SWF!T.ttf]])
LSM:Register(MediaType_FONT, "Taurus", [[Interface\AddOns\VSM\Media\Fonts\Taurus.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Tellural Alt", [[Interface\AddOns\VSM\Media\Fonts\TelluralAlt.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "TGL", [[Interface\AddOns\VSM\Media\Fonts\TGL.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Trashco", [[Interface\AddOns\VSM\Media\Fonts\Trashco.ttf]])
LSM:Register(MediaType_FONT, "TrashHand", [[Interface\AddOns\VSM\Media\Fonts\TrashHand.ttf]])
LSM:Register(MediaType_FONT, "Triatlhon In", [[Interface\AddOns\VSM\Media\Fonts\TriatlhonIn.ttf]])
LSM:Register(MediaType_FONT, "Ubuntu Condensed", [[Interface\AddOns\VSM\Media\Fonts\UbuntuCondensed.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Ubuntu Light", [[Interface\AddOns\VSM\Media\Fonts\UbuntuLight.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Waltograph UI", [[Interface\AddOns\VSM\Media\Fonts\WaltographUI.ttf]])
LSM:Register(MediaType_FONT, "WenQuanYi Zen Hei", [[Interface\AddOns\VSM\Media\Fonts\WenQuanYiZenHei.ttf]], koKR + ruRU + zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "X360", [[Interface\AddOns\VSM\Media\Fonts\X360.ttf]], ruRU + western)
LSM:Register(MediaType_FONT, "Yanone Kaffeesatz Regular", [[Interface\AddOns\VSM\Media\Fonts\YanoneKaffeesatzRegular.ttf]])
LSM:Register(MediaType_FONT, "Yellowjacket", [[Interface\AddOns\VSM\Media\Fonts\Yellowjacket.ttf]])
LSM:Register(MediaType_FONT, 'Tukui Pixel', [[Interface\AddOns\VSM\Media\Fonts\Visitor.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Tukui Combat', [[Interface\AddOns\VSM\Media\Fonts\Diediedie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register(MediaType_FONT, 'Tukui UnitFrame', [[Interface\AddOns\VSM\Media\Fonts\BigNoodleTitling.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)

LSM:Register(MediaType_SOUND, 'Инопрешеленец', [[Interface\AddOns\VSM\Media\Meme\inopreshelenec.ogg]])
LSM:Register(MediaType_SOUND, 'Warning', [[Interface\AddOns\VSM\Media\Sounds\Warning.mp3]])
LSM:Register(MediaType_SOUND, 'Тройная дизмораль', [[Interface\AddOns\VSM\Media\Sounds\Voodoshtripple.mp3]])
LSM:Register(MediaType_SOUND, 'Миша ну БАБЛ', [[Interface\AddOns\VSM\Media\Sounds\mishababl.mp3]])
LSM:Register(MediaType_SOUND, 'Миша хватит косячить', [[Interface\AddOns\VSM\Media\Sounds\Hvatit Kosyachit.mp3]])
LSM:Register(MediaType_SOUND, 'БЕРЕГИТЕСЬ', [[Interface\AddOns\VSM\Media\Sounds\BEREGITES.ogg]])
LSM:Register(MediaType_SOUND, 'Ааааа Вопль', [[Interface\AddOns\VSM\Media\Meme\AAAA_lew.ogg]])
LSM:Register(MediaType_SOUND, 'Ааааа Гачи', [[Interface\AddOns\VSM\Media\Meme\AAAAA.ogg]])
LSM:Register(MediaType_SOUND, 'Ты Арестован Парень', [[Interface\AddOns\VSM\Media\Meme\arestovan.ogg]])
LSM:Register(MediaType_SOUND, 'Ты Баклажан', [[Interface\AddOns\VSM\Media\Meme\baklazhan.ogg]])
LSM:Register(MediaType_SOUND, 'Бляяяять', [[Interface\AddOns\VSM\Media\Meme\bearform.ogg]])
LSM:Register(MediaType_SOUND, 'Блейдшторм', [[Interface\AddOns\VSM\Media\Meme\bladestorm.ogg]])
LSM:Register(MediaType_SOUND, 'Бочок Потик', [[Interface\AddOns\VSM\Media\Meme\bochok.ogg]])
LSM:Register(MediaType_SOUND, 'Бомба Раздефужена', [[Interface\AddOns\VSM\Media\Meme\bomb_d.ogg]])
LSM:Register(MediaType_SOUND, 'Бомба Установлена', [[Interface\AddOns\VSM\Media\Meme\bomb_p.ogg]])
LSM:Register(MediaType_SOUND, 'Чики Брики', [[Interface\AddOns\VSM\Media\Meme\cheeki-breeki.ogg]])
LSM:Register(MediaType_SOUND, 'Чего Блять', [[Interface\AddOns\VSM\Media\Meme\chegob.ogg]])
LSM:Register(MediaType_SOUND, 'Циган Айдидидай', [[Interface\AddOns\VSM\Media\Meme\cigan.ogg]])
LSM:Register(MediaType_SOUND, 'Убирай Дрочило', [[Interface\AddOns\VSM\Media\Meme\disarm.ogg]])
LSM:Register(MediaType_SOUND, 'Снимай штаны и доставай', [[Interface\AddOns\VSM\Media\Meme\disarm_2.ogg]])
LSM:Register(MediaType_SOUND, 'Диджей Ебан', [[Interface\AddOns\VSM\Media\Meme\djeban.ogg]])
LSM:Register(MediaType_SOUND, 'У меня Джип', [[Interface\AddOns\VSM\Media\Meme\djeep.ogg]])
LSM:Register(MediaType_SOUND, 'Lot of Damage', [[Interface\AddOns\VSM\Media\Meme\dmg.ogg]])
LSM:Register(MediaType_SOUND, 'Dps slowly', [[Interface\AddOns\VSM\Media\Meme\dpsslowly.ogg]])
LSM:Register(MediaType_SOUND, 'Dramartic', [[Interface\AddOns\VSM\Media\Meme\dramartic.ogg]])
LSM:Register(MediaType_SOUND, 'Нахуя Дудосить', [[Interface\AddOns\VSM\Media\Meme\dudos.ogg]])
LSM:Register(MediaType_SOUND, 'Йобаный рот', [[Interface\AddOns\VSM\Media\Meme\ebany_rot.ogg]])
LSM:Register(MediaType_SOUND, 'Enemy spoted', [[Interface\AddOns\VSM\Media\Meme\enemy_spot.ogg]])
LSM:Register(MediaType_SOUND, 'Ержан вставай', [[Interface\AddOns\VSM\Media\Meme\erjan.ogg]])
LSM:Register(MediaType_SOUND, 'FBI опен ап', [[Interface\AddOns\VSM\Media\Meme\FBI.ogg]])
LSM:Register(MediaType_SOUND, 'Беги сука беги', [[Interface\AddOns\VSM\Media\Meme\fear2.ogg]])
LSM:Register(MediaType_SOUND, 'Это фиаско братан', [[Interface\AddOns\VSM\Media\Meme\fiasco.ogg]])
LSM:Register(MediaType_SOUND, 'Граната из КС', [[Interface\AddOns\VSM\Media\Meme\fireinthe.ogg]])
LSM:Register(MediaType_SOUND, 'Прекрати разврат', [[Interface\AddOns\VSM\Media\Meme\greshnik.ogg]])
LSM:Register(MediaType_SOUND, 'Хардбас', [[Interface\AddOns\VSM\Media\Meme\hardbass.ogg]])
LSM:Register(MediaType_SOUND, 'Попробуй меня трахнуть', [[Interface\AddOns\VSM\Media\Meme\idisuda.ogg]])
LSM:Register(MediaType_SOUND, 'Имолейт Импрувед', [[Interface\AddOns\VSM\Media\Meme\impruved.ogg]])
LSM:Register(MediaType_SOUND, 'Джон Сина', [[Interface\AddOns\VSM\Media\Meme\jhoncena.ogg]])
LSM:Register(MediaType_SOUND, 'Ты внатуре кабан', [[Interface\AddOns\VSM\Media\Meme\kaban.ogg]])
LSM:Register(MediaType_SOUND, 'Давай прыгай', [[Interface\AddOns\VSM\Media\Meme\kakashka.ogg]])
LSM:Register(MediaType_SOUND, 'Да каке ебнуть', [[Interface\AddOns\VSM\Media\Meme\kakebnut.ogg]])
LSM:Register(MediaType_SOUND, 'Как так то а', [[Interface\AddOns\VSM\Media\Meme\kaktak.ogg]])
LSM:Register(MediaType_SOUND, 'Ебаный рот казино', [[Interface\AddOns\VSM\Media\Meme\kazino_1.ogg]])
LSM:Register(MediaType_SOUND, 'Ебаный твой рот', [[Interface\AddOns\VSM\Media\Meme\kazino_2.ogg]])
LSM:Register(MediaType_SOUND, 'Kill Them', [[Interface\AddOns\VSM\Media\Meme\killthem.ogg]])
LSM:Register(MediaType_SOUND, 'Пошел ты козел', [[Interface\AddOns\VSM\Media\Meme\kozel.ogg]])
LSM:Register(MediaType_SOUND, 'Левиосаааа', [[Interface\AddOns\VSM\Media\Meme\leviosa.ogg]])
LSM:Register(MediaType_SOUND, 'Ватафакмазафак', [[Interface\AddOns\VSM\Media\Meme\mazafak.ogg]])
LSM:Register(MediaType_SOUND, 'По новой Миша', [[Interface\AddOns\VSM\Media\Meme\misha.ogg]])
LSM:Register(MediaType_SOUND, 'Мор Дотс', [[Interface\AddOns\VSM\Media\Meme\moredots.ogg]])
LSM:Register(MediaType_SOUND, 'Муда муда муда', [[Interface\AddOns\VSM\Media\Meme\muda.ogg]])
LSM:Register(MediaType_SOUND, 'Ну Нахер', [[Interface\AddOns\VSM\Media\Meme\naher.ogg]])
LSM:Register(MediaType_SOUND, 'Нормально', [[Interface\AddOns\VSM\Media\Meme\namalno.ogg]])
LSM:Register(MediaType_SOUND, 'нет Мозга', [[Interface\AddOns\VSM\Media\Meme\netmozga.ogg]])
LSM:Register(MediaType_SOUND, 'Невыдерживаю', [[Interface\AddOns\VSM\Media\Meme\neviderj.ogg]])
LSM:Register(MediaType_SOUND, 'Нойс', [[Interface\AddOns\VSM\Media\Meme\noice.ogg]])
LSM:Register(MediaType_SOUND, 'Майнкрафт урон', [[Interface\AddOns\VSM\Media\Meme\oh.ogg]])
LSM:Register(MediaType_SOUND, 'Айм Сори', [[Interface\AddOns\VSM\Media\Meme\ohshit.ogg]])
LSM:Register(MediaType_SOUND, 'Омаоа шиндеау', [[Interface\AddOns\VSM\Media\Meme\omaeva.ogg]])
LSM:Register(MediaType_SOUND, 'Отходите пожалуйста', [[Interface\AddOns\VSM\Media\Meme\othodi.ogg]])
LSM:Register(MediaType_SOUND, 'Палку давай', [[Interface\AddOns\VSM\Media\Meme\palku.ogg]])
LSM:Register(MediaType_SOUND, 'Пизда Рулю', [[Interface\AddOns\VSM\Media\Meme\pizdaruly.ogg]])
LSM:Register(MediaType_SOUND, 'Отходите подальше', [[Interface\AddOns\VSM\Media\Meme\podalshe.ogg]])
LSM:Register(MediaType_SOUND, 'Покайся Грешник', [[Interface\AddOns\VSM\Media\Meme\pokaysya.ogg]])
LSM:Register(MediaType_SOUND, 'Погнали нахуй', [[Interface\AddOns\VSM\Media\Meme\pull.ogg]])
LSM:Register(MediaType_SOUND, 'Мужицкий дождь', [[Interface\AddOns\VSM\Media\Meme\rain.ogg]])
LSM:Register(MediaType_SOUND, 'Крайне мала', [[Interface\AddOns\VSM\Media\Meme\resist.ogg]])
LSM:Register(MediaType_SOUND, 'Ран', [[Interface\AddOns\VSM\Media\Meme\run.ogg]])
LSM:Register(MediaType_SOUND, 'Че серьезно', [[Interface\AddOns\VSM\Media\Meme\serezno.ogg]])
LSM:Register(MediaType_SOUND, 'Шааааааа', [[Interface\AddOns\VSM\Media\Meme\sha.ogg]])
LSM:Register(MediaType_SOUND, 'Снуп Дог', [[Interface\AddOns\VSM\Media\Meme\snoopdog.ogg]])
LSM:Register(MediaType_SOUND, 'Стартуем', [[Interface\AddOns\VSM\Media\Meme\startyem.ogg]])
LSM:Register(MediaType_SOUND, 'Время стопать', [[Interface\AddOns\VSM\Media\Meme\stop.ogg]])
LSM:Register(MediaType_SOUND, 'ШАФЕР БИТЧ', [[Interface\AddOns\VSM\Media\Meme\suffer_bitch.ogg]])
LSM:Register(MediaType_SOUND, 'Сурпрайз Мазафака', [[Interface\AddOns\VSM\Media\Meme\surprise.ogg]])
LSM:Register(MediaType_SOUND, 'Тааааааа', [[Interface\AddOns\VSM\Media\Meme\taa.ogg]])
LSM:Register(MediaType_SOUND, 'Ю тач май тралала', [[Interface\AddOns\VSM\Media\Meme\talala.ogg]])
LSM:Register(MediaType_SOUND, 'Продолжение следует', [[Interface\AddOns\VSM\Media\Meme\tobecon.ogg]])
LSM:Register(MediaType_SOUND, 'Толик Еболик', [[Interface\AddOns\VSM\Media\Meme\tolik.ogg]])
LSM:Register(MediaType_SOUND, 'Ама вирджин', [[Interface\AddOns\VSM\Media\Meme\virgin.ogg]])
LSM:Register(MediaType_SOUND, 'Больно в ноге', [[Interface\AddOns\VSM\Media\Meme\vnoge.ogg]])
LSM:Register(MediaType_SOUND, 'Велком ту зе клаб', [[Interface\AddOns\VSM\Media\Meme\welcome.ogg]])
LSM:Register(MediaType_SOUND, 'Вау', [[Interface\AddOns\VSM\Media\Meme\wow.ogg]])
LSM:Register(MediaType_SOUND, 'Я вас не звал', [[Interface\AddOns\VSM\Media\Meme\ya_vas_ne_zval.ogg]])
LSM:Register(MediaType_SOUND, 'Яйцами пезднулся', [[Interface\AddOns\VSM\Media\Meme\yaytsami.ogg]])
LSM:Register(MediaType_SOUND, 'Бро', [[Interface\AddOns\VSM\Media\Meme2\brue.mp3]])
LSM:Register(MediaType_SOUND, 'Да ну нахуй', [[Interface\AddOns\VSM\Media\Meme2\da-nu-nahy.mp3]])
LSM:Register(MediaType_SOUND, 'Да ладна', [[Interface\AddOns\VSM\Media\Meme2\daladna.mp3]])
LSM:Register(MediaType_SOUND, 'Да всем насрать', [[Interface\AddOns\VSM\Media\Meme2\da-vsem-nasrt.mp3]])
LSM:Register(MediaType_SOUND, 'Ералаш', [[Interface\AddOns\VSM\Media\Meme2\eralash.mp3]])
LSM:Register(MediaType_SOUND, 'Юху минус три', [[Interface\AddOns\VSM\Media\Meme2\es-minus-ehuuu.mp3]])
LSM:Register(MediaType_SOUND, 'Фак фак фак', [[Interface\AddOns\VSM\Media\Meme2\fak-fak-faaaaak.mp3]])
LSM:Register(MediaType_SOUND, 'Найн найн найн', [[Interface\AddOns\VSM\Media\Meme2\golos-beshenogo-gitlera-iz-mema-kotoryiy-nesoglasen.mp3]])
LSM:Register(MediaType_SOUND, 'Хелло мазафака', [[Interface\AddOns\VSM\Media\Meme2\hello.mp3]])
LSM:Register(MediaType_SOUND, 'Кто куда а я', [[Interface\AddOns\VSM\Media\Meme2\kto-kuda-a-ya-po-delam.mp3]])
LSM:Register(MediaType_SOUND, 'Лежать плюс', [[Interface\AddOns\VSM\Media\Meme2\-lejat-sasat.mp3]])
LSM:Register(MediaType_SOUND, 'Ля ты крыса', [[Interface\AddOns\VSM\Media\Meme2\lya-tyi-kryisa1.mp3]])
LSM:Register(MediaType_SOUND, 'Мальчик иди отсюда', [[Interface\AddOns\VSM\Media\Meme2\malchik-idi-otsyuda.mp3]])
LSM:Register(MediaType_SOUND, 'Продолжение следует', [[Interface\AddOns\VSM\Media\Meme2\mem-okontsovka-filma-to-be-continued.mp3]])
LSM:Register(MediaType_SOUND, 'Музончик', [[Interface\AddOns\VSM\Media\Meme2\muzyika-dlya-krutogo-momenta.mp3]])
LSM:Register(MediaType_SOUND, 'На нас напали', [[Interface\AddOns\VSM\Media\Meme2\na-nas-napali.mp3]])
LSM:Register(MediaType_SOUND, 'Не, нихуя', [[Interface\AddOns\VSM\Media\Meme2\ne-nihya.mp3]])
LSM:Register(MediaType_SOUND, 'О привет!', [[Interface\AddOns\VSM\Media\Meme2\o-privet.mp3]])
LSM:Register(MediaType_SOUND, 'Плохо мне(((', [[Interface\AddOns\VSM\Media\Meme2\ploho-mne.mp3]])
LSM:Register(MediaType_SOUND, 'Пожили и хватит', [[Interface\AddOns\VSM\Media\Meme2\pojili-i-hvatit.mp3]])
LSM:Register(MediaType_SOUND, 'Пришел увидел', [[Interface\AddOns\VSM\Media\Meme2\prishel-uvidel.mp3]])
LSM:Register(MediaType_SOUND, 'Пук', [[Interface\AddOns\VSM\Media\Meme2\puk.mp3]])
LSM:Register(MediaType_SOUND, 'Шизофрения', [[Interface\AddOns\VSM\Media\Meme2\shizofreniya.mp3]])
LSM:Register(MediaType_SOUND, 'Кудасай', [[Interface\AddOns\VSM\Media\Meme2\slezyi-sopli.mp3]])
LSM:Register(MediaType_SOUND, 'Страшно очень страшно', [[Interface\AddOns\VSM\Media\Meme2\strashno-ochen-strashno.mp3]])
LSM:Register(MediaType_SOUND, 'Тутутутуту', [[Interface\AddOns\VSM\Media\Meme2\tutututu-mem-demotivator.mp3]])
LSM:Register(MediaType_SOUND, 'У меня есть такой план', [[Interface\AddOns\VSM\Media\Meme2\u-menya-est-takoi-plan.mp3]])
LSM:Register(MediaType_SOUND, 'Утро доброе', [[Interface\AddOns\VSM\Media\Meme2\utro-dobroe.mp3]])
LSM:Register(MediaType_SOUND, 'Внатуре класс', [[Interface\AddOns\VSM\Media\Meme2\v-nature-klass.mp3]])
LSM:Register(MediaType_SOUND, 'Расмешнило', [[Interface\AddOns\VSM\Media\Meme2\vot-tyi-menya-rassmeshil.mp3]])
LSM:Register(MediaType_SOUND, 'Всего хо ро ше го', [[Interface\AddOns\VSM\Media\Meme2\vsego-horoshego.mp3]])
LSM:Register(MediaType_SOUND, 'Я что похож на абонента', [[Interface\AddOns\VSM\Media\Meme2\ya-chto-pohoj-na-abonenta.mp3]])
LSM:Register(MediaType_SOUND, 'Занято нахуй', [[Interface\AddOns\VSM\Media\Meme2\zanyato.mp3]])
LSM:Register(MediaType_SOUND, 'Здарова братиш', [[Interface\AddOns\VSM\Media\Meme2\zdorovo-bratish.mp3]])
LSM:Register(MediaType_SOUND, '1 Ооооу сука', [[Interface\AddOns\VSM\Media\Meme2\cartoon_fof.ogg]])
LSM:Register(MediaType_SOUND, '1 Лабудабудаб', [[Interface\AddOns\VSM\Media\Meme2\cartoon_ffb.ogg]])
LSM:Register(MediaType_SOUND, '1 Алах Акбар', [[Interface\AddOns\VSM\Media\Meme2\cartoon_hs.ogg]])
LSM:Register(MediaType_SOUND, '1 Пахлава', [[Interface\AddOns\VSM\Media\Meme2\voice_lowhp.ogg]])
LSM:Register(MediaType_SOUND, '1A Nyaaaaa', [[Interface\AddOns\VSM\Media\Meme2\anime_fof.ogg]])
LSM:Register(MediaType_SOUND, '1A Sprint', [[Interface\AddOns\VSM\Media\Meme2\anime_sprint.ogg]])
LSM:Register(MediaType_SOUND, '1 MCeat', [[Interface\AddOns\VSM\Media\Meme2\MC_eat.ogg]])
LSM:Register(MediaType_SOUND, '1A Wait', [[Interface\AddOns\VSM\Media\Meme2\anime_cc.ogg]])
LSM:Register(MediaType_SOUND, '1 Богдан любит', [[Interface\AddOns\VSM\Media\Meme2\mem_bogdan.ogg]])
LSM:Register(MediaType_SOUND, '1A UWU', [[Interface\AddOns\VSM\Media\Meme2\anime_uwu.ogg]])
LSM:Register(MediaType_SOUND, '1 Beep Beep', [[Interface\AddOns\VSM\Media\Meme2\cartoon_roadrunner.ogg]])
LSM:Register(MediaType_SOUND, '1 tarkov', [[Interface\AddOns\VSM\Media\Meme2\mem_tarkov.ogg]])
LSM:Register(MediaType_SOUND, '1 Hard Fart', [[Interface\AddOns\VSM\Media\Meme2\mem_fart.ogg]])
LSM:Register(MediaType_SOUND, '1 MChurt', [[Interface\AddOns\VSM\Media\Meme2\MC_hurt.ogg]])
LSM:Register(MediaType_SOUND, 'Чумба', [[Interface\AddOns\VSM\Media\Meme2\Чумба.mp3]])
LSM:Register(MediaType_SOUND, 'Изатерика', [[Interface\AddOns\VSM\Media\Meme2\izaterika.mp3]])
LSM:Register(MediaType_SOUND, 'ВнеЗаПнО', [[Interface\AddOns\VSM\Media\Meme2\vnezapno.ogg]])
LSM:Register(MediaType_SOUND, 'ПАМИНУТНО', [[Interface\AddOns\VSM\Media\Meme2\Soloka.mp3]])

LSM:Register(MediaType_BORDER, "Ferous 1", [[Interface\AddOns\VSM\Media\Borders\Ferous1.tga]])
LSM:Register(MediaType_BORDER, "Ferous 2", [[Interface\AddOns\VSM\Media\Borders\Ferous2.tga]])
LSM:Register(MediaType_BORDER, "Ferous 3", [[Interface\AddOns\VSM\Media\Borders\Ferous3.tga]])
LSM:Register(MediaType_BORDER, "Ferous 4", [[Interface\AddOns\VSM\Media\Borders\Ferous4.tga]])
LSM:Register(MediaType_BORDER, "Ferous 5", [[Interface\AddOns\VSM\Media\Borders\Ferous5.tga]])
LSM:Register(MediaType_BORDER, "Ferous 6", [[Interface\AddOns\VSM\Media\Borders\Ferous6.tga]])
LSM:Register(MediaType_BORDER, "Ferous 7", [[Interface\AddOns\VSM\Media\Borders\Ferous7.tga]])
LSM:Register(MediaType_BORDER, "Ferous 8", [[Interface\AddOns\VSM\Media\Borders\Ferous8.tga]])
LSM:Register(MediaType_BORDER, "Ferous 9", [[Interface\AddOns\VSM\Media\Borders\Ferous9.tga]])
LSM:Register(MediaType_BORDER, "Ferous 10", [[Interface\AddOns\VSM\Media\Borders\Ferous10.tga]])
LSM:Register(MediaType_BORDER, "Ferous 11", [[Interface\AddOns\VSM\Media\Borders\Ferous11.tga]])
LSM:Register(MediaType_BORDER, "Ferous 12", [[Interface\AddOns\VSM\Media\Borders\Ferous12.tga]])
LSM:Register(MediaType_BORDER, "Ferous 13", [[Interface\AddOns\VSM\Media\Borders\Ferous13.tga]])
LSM:Register(MediaType_BORDER, "Raeli Glow", [[Interface\AddOns\VSM\Media\Borders\RaeliGlow.tga]])
LSM:Register(MediaType_BORDER, "Raeli Glow Small", [[Interface\AddOns\VSM\Media\Borders\RaeliGlowSmall.tga]])
LSM:Register(MediaType_BORDER, "RothSquare", [[Interface\AddOns\VSM\Media\Borders\RothSquare.tga]])
LSM:Register(MediaType_BORDER, "SeerahScalloped", [[Interface\AddOns\VSM\Media\Borders\SeerahScalloped.blp]])
LSM:Register(MediaType_BORDER, "Text Panel border", [[Interface\GLUES\COMMON\TextPanel-Borders.blp]])
LSM:Register(MediaType_BORDER, "Wood border", [[Interface\AchievementFrame\UI-Achievement-WoodBorder.blp]])

LSM:Register(MediaType_BACKGROUND, "Bricks", [[Interface\AddOns\VSM\Media\Backgrounds\Bricks.tga]])
LSM:Register(MediaType_BACKGROUND, "Brushed Metal", [[Interface\AddOns\VSM\Media\Backgrounds\Brushedmetal.tga]])
LSM:Register(MediaType_BACKGROUND, "Copper", [[Interface\AddOns\VSM\Media\Backgrounds\Copper.tga]])
LSM:Register(MediaType_BACKGROUND, "Moo", [[Interface\AddOns\VSM\Media\Backgrounds\Moo.tga]])
LSM:Register(MediaType_BACKGROUND, "Overlay Rect", [[Interface\AddOns\VSM\Media\Backgrounds\OverlayRect.tga]])
LSM:Register(MediaType_BACKGROUND, "Screen Overlay", [[Interface\AddOns\VSM\Media\Backgrounds\ScreenOverlay.tga]])
LSM:Register(MediaType_BACKGROUND, "Smoke", [[Interface\AddOns\VSM\Media\Backgrounds\Smoke.tga]])

if not select(4, GetAddOnInfo('WeakAuras')) then
	Private.texture_types = {
	["Kozloff"] = {
    ["Interface\\AddOns\\VSM\\Media\\Textures\\griph_1"] = "griph_1",
	["Interface\\AddOns\\VSM\\Media\\Textures\\griph_2"] = "griph_2",
	["Interface\\AddOns\\VSM\\Media\\Textures\\griph_3"] = "griph_3",
	["Interface\\AddOns\\VSM\\Media\\Textures\\griph_4"] = "griph_4",
	["Interface\\AddOns\\VSM\\Media\\Textures\\griph_5"] = "griph_5",
	["Interface\\AddOns\\VSM\\Media\\Textures\\proc_1"] = "proc_1",
	["Interface\\AddOns\\VSM\\Media\\Textures\\proc_2"] = "proc_2",
	["Interface\\AddOns\\VSM\\Media\\Textures\\proc_cc"] = "griph_cc",
	["Interface\\AddOns\\VSM\\Media\\Textures\\proc_ffb"] = "griph_ffb",
	["Interface\\AddOns\\VSM\\Media\\Textures\\proc_fof_1"] = "proc_fof_1",
	["Interface\\AddOns\\VSM\\Media\\Textures\\proc_fof_2"] = "proc_fof_2",
	["Interface\\AddOns\\VSM\\Media\\Textures\\proc_lowhp"] = "proc_lowhp",
	["Interface\\AddOns\\VSM\\Media\\Textures\\proc_sprint"] = "proc_sprint",
	},
}
end

if not select(4, GetAddOnInfo('ElvUI')) then
	LSM:Register(MediaType_FONT, 'ElvUI Alt-Combat', [[Interface\AddOns\VSM\Media\Fonts\Diediedie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register(MediaType_FONT, 'ElvUI Alt-Font', [[Interface\AddOns\VSM\Media\Fonts\ContinuumMedium.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register(MediaType_FONT, 'ElvUI Combat', [[Interface\AddOns\VSM\Media\Fonts\ActionMan.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register(MediaType_FONT, 'ElvUI Font', [[Interface\AddOns\VSM\Media\Fonts\PTSansNarrow-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register(MediaType_FONT, 'ElvUI Pixel', [[Interface\AddOns\VSM\Media\Fonts\Homespun.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register(MediaType_STATUSBAR, 'ElvUI Gloss', [[Interface\AddOns\VSM\Media\StatusBars\ElvUI]])
end
